
package org.muhia.app.psi.integ.wsdl.mpesa.paymentvalidationandconfirmation.paymentvalidationandconfirmation;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "C2BPaymentValidationAndConfirmationService", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", wsdlLocation = "src/main/resources/apis/CBPInterface_C2BPaymentValidationAndConfirmation.wsdl")
public class C2BPaymentValidationAndConfirmationService
        extends Service {

    private final static URL C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_EXCEPTION;
    private final static QName C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_QNAME = new QName("http://cps.huawei.com/cpsinterface/c2bpayment", "C2BPaymentValidationAndConfirmationService");

    static {
        C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_WSDL_LOCATION = C2BPaymentValidationAndConfirmationService.class.getResource("src/main/resources/apis/CBPInterface_C2BPaymentValidationAndConfirmation.wsdl");
        WebServiceException e = null;
        if (C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'src/main/resources/apis/CBPInterface_C2BPaymentValidationAndConfirmation.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_EXCEPTION = e;
    }

    public C2BPaymentValidationAndConfirmationService() {
        super(__getWsdlLocation(), C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_QNAME);
    }

    public C2BPaymentValidationAndConfirmationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_QNAME, features);
    }

    public C2BPaymentValidationAndConfirmationService(URL wsdlLocation) {
        super(wsdlLocation, C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_QNAME);
    }

    public C2BPaymentValidationAndConfirmationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_QNAME, features);
    }

    public C2BPaymentValidationAndConfirmationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public C2BPaymentValidationAndConfirmationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_EXCEPTION != null) {
            throw C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_EXCEPTION;
        }
        return C2BPAYMENTVALIDATIONANDCONFIRMATIONSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns C2BPaymentValidationAndComfirmation
     */
    @WebEndpoint(name = "C2BPaymentValidationAndConfirmationServicePort")
    public C2BPaymentValidationAndComfirmation getC2BPaymentValidationAndConfirmationServicePort() {
        return super.getPort(new QName("http://cps.huawei.com/cpsinterface/c2bpayment", "C2BPaymentValidationAndConfirmationServicePort"), C2BPaymentValidationAndComfirmation.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns C2BPaymentValidationAndComfirmation
     */
    @WebEndpoint(name = "C2BPaymentValidationAndConfirmationServicePort")
    public C2BPaymentValidationAndComfirmation getC2BPaymentValidationAndConfirmationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cps.huawei.com/cpsinterface/c2bpayment", "C2BPaymentValidationAndConfirmationServicePort"), C2BPaymentValidationAndComfirmation.class, features);
    }

}
