
package org.muhia.app.psi.integ.wsdl.mpesa.paymentvalidationandconfirmation.paymentvalidationandconfirmation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "C2BPaymentValidationAndComfirmation", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface C2BPaymentValidationAndComfirmation {


    /**
     * @param c2BPaymentValidationRequest
     * @return returns org.muhia.app.psi.integ.wsdl.mpesa.paymentvalidationandconfirmation.C2BPaymentValidationResult
     */
    @WebMethod(operationName = "ValidateC2BPayment", action = "ValidateC2BPayment")
    @WebResult(name = "C2BPaymentValidationResult", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", partName = "C2BPaymentValidationResult")
    C2BPaymentValidationResult validateC2BPayment(
            @WebParam(name = "C2BPaymentValidationRequest", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", partName = "C2BPaymentValidationRequest")
                    C2BPaymentValidationRequest c2BPaymentValidationRequest);

    /**
     * @param c2BPaymenConfirmationRequest
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ConfirmC2BPayment", action = "ConfirmC2BPayment")
    @WebResult(name = "C2BPaymentConfirmationResult", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", partName = "C2BPaymentConfirmationResult")
    String confirmC2BPayment(
            @WebParam(name = "C2BPaymentConfirmationRequest", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", partName = "C2BPaymenConfirmationRequest")
                    C2BPaymentConfirmationRequest c2BPaymenConfirmationRequest);

}
