
package org.muhia.app.psi.integ.wsdl.mpesa.cbp.request;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RequestMgrService", targetNamespace = "http://api-v1.gen.mm.vodafone.com/mminterface/request", wsdlLocation = "apis/CBPInterface_Request.wsdl")
public class RequestMgrService
    extends Service
{

    private final static URL REQUESTMGRSERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUESTMGRSERVICE_EXCEPTION;
    private final static QName REQUESTMGRSERVICE_QNAME = new QName("http://api-v1.gen.mm.vodafone.com/mminterface/request", "RequestMgrService");

    static {
        REQUESTMGRSERVICE_WSDL_LOCATION = org.muhia.app.psi.integ.wsdl.mpesa.cbp.request.RequestMgrService.class.getResource("apis/CBPInterface_Request.wsdl");
        WebServiceException e = null;
        if (REQUESTMGRSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'apis/CBPInterface_Request.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        REQUESTMGRSERVICE_EXCEPTION = e;
    }

    public RequestMgrService() {
        super(__getWsdlLocation(), REQUESTMGRSERVICE_QNAME);
    }

    public RequestMgrService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REQUESTMGRSERVICE_QNAME, features);
    }

    public RequestMgrService(URL wsdlLocation) {
        super(wsdlLocation, REQUESTMGRSERVICE_QNAME);
    }

    public RequestMgrService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REQUESTMGRSERVICE_QNAME, features);
    }

    public RequestMgrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequestMgrService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RequestMgrPortType
     */
    @WebEndpoint(name = "RequestMgrServicePort")
    public RequestMgrPortType getRequestMgrServicePort() {
        return super.getPort(new QName("http://api-v1.gen.mm.vodafone.com/mminterface/request", "RequestMgrServicePort"), RequestMgrPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestMgrPortType
     */
    @WebEndpoint(name = "RequestMgrServicePort")
    public RequestMgrPortType getRequestMgrServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api-v1.gen.mm.vodafone.com/mminterface/request", "RequestMgrServicePort"), RequestMgrPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REQUESTMGRSERVICE_EXCEPTION!= null) {
            throw REQUESTMGRSERVICE_EXCEPTION;
        }
        return REQUESTMGRSERVICE_WSDL_LOCATION;
    }

}
