
package org.muhia.app.psi.integ.wsdl.am.merchant.query;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "MerchantQueryWebService", targetNamespace = "http://www.zain.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MerchantQueryWebService {


    /**
     * @param passWord
     * @param timeFrom
     * @param timeTo
     * @param userName
     * @return returns org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionsResponse
     */
    @WebMethod(operationName = "RequestTransactionByTimeInterval", action = "RequestTransactionByTimeInterval")
    @WebResult(name = "RequestTransactionByTimeIntervalResult", targetNamespace = "http://www.zain.com/")
    @RequestWrapper(localName = "RequestTransactionByTimeInterval", targetNamespace = "http://www.zain.com/", className = "org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionByTimeInterval")
    @ResponseWrapper(localName = "RequestTransactionByTimeIntervalResponse", targetNamespace = "http://www.zain.com/", className = "org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionByTimeIntervalResponse")
    RequestTransactionsResponse requestTransactionByTimeInterval(
            @WebParam(name = "userName", targetNamespace = "http://www.zain.com/")
                    String userName,
            @WebParam(name = "passWord", targetNamespace = "http://www.zain.com/")
                    String passWord,
            @WebParam(name = "timeFrom", targetNamespace = "http://www.zain.com/")
                    String timeFrom,
            @WebParam(name = "timeTo", targetNamespace = "http://www.zain.com/")
                    String timeTo);

    /**
     * @param passWord
     * @param timeFrom
     * @param timeTo
     * @param userName
     * @return returns org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionsResponse
     */
    @WebMethod(operationName = "RequestTransactionByTimeIntervalDetailed", action = "RequestTransactionByTimeIntervalDetailed")
    @WebResult(name = "RequestTransactionByTimeIntervalDetailedResult", targetNamespace = "http://www.zain.com/")
    @RequestWrapper(localName = "RequestTransactionByTimeIntervalDetailed", targetNamespace = "http://www.zain.com/", className = "org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionByTimeIntervalDetailed")
    @ResponseWrapper(localName = "RequestTransactionByTimeIntervalDetailedResponse", targetNamespace = "http://www.zain.com/", className = "org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionByTimeIntervalDetailedResponse")
    RequestTransactionsResponse requestTransactionByTimeIntervalDetailed(
            @WebParam(name = "userName", targetNamespace = "http://www.zain.com/")
                    String userName,
            @WebParam(name = "passWord", targetNamespace = "http://www.zain.com/")
                    String passWord,
            @WebParam(name = "timeFrom", targetNamespace = "http://www.zain.com/")
                    String timeFrom,
            @WebParam(name = "timeTo", targetNamespace = "http://www.zain.com/")
                    String timeTo);

    /**
     * @param passWord
     * @param userName
     * @param msisdn
     * @param referenceId
     * @return returns org.muhia.app.psi.integ.wsdl.am.merchant.query.Response
     */
    @WebMethod(operationName = "RequestTransaction", action = "RequestTransaction")
    @WebResult(name = "RequestTransactionResult", targetNamespace = "http://www.zain.com/")
    @RequestWrapper(localName = "RequestTransaction", targetNamespace = "http://www.zain.com/", className = "org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransaction")
    @ResponseWrapper(localName = "RequestTransactionResponse", targetNamespace = "http://www.zain.com/", className = "org.muhia.app.psi.integ.wsdl.am.merchant.query.RequestTransactionResponse")
    Response requestTransaction(
            @WebParam(name = "userName", targetNamespace = "http://www.zain.com/")
                    String userName,
            @WebParam(name = "passWord", targetNamespace = "http://www.zain.com/")
                    String passWord,
            @WebParam(name = "referenceId", targetNamespace = "http://www.zain.com/")
                    String referenceId,
            @WebParam(name = "msisdn", targetNamespace = "http://www.zain.com/")
                    String msisdn);

}
