
package org.muhia.app.psi.integ.wsdl.am.bulkpayment;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "BulkPaymentWebServiceNewService", targetNamespace = "http://www.obopay.com/xml/bulkpayment/v1", wsdlLocation = "apis/AirtelMoneyMerchantPaymentService.wsdl")
public class BulkPaymentWebServiceNewService
        extends Service {

    private final static URL BULKPAYMENTWEBSERVICENEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException BULKPAYMENTWEBSERVICENEWSERVICE_EXCEPTION;
    private final static QName BULKPAYMENTWEBSERVICENEWSERVICE_QNAME = new QName("http://www.obopay.com/xml/bulkpayment/v1", "BulkPaymentWebServiceNewService");

    static {
        BULKPAYMENTWEBSERVICENEWSERVICE_WSDL_LOCATION = org.muhia.app.psi.integ.wsdl.am.bulkpayment.BulkPaymentWebServiceNewService.class.getResource("apis/AirtelMoneyMerchantPaymentService.wsdl");
        WebServiceException e = null;
        if (BULKPAYMENTWEBSERVICENEWSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'apis/AirtelMoneyMerchantPaymentService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BULKPAYMENTWEBSERVICENEWSERVICE_EXCEPTION = e;
    }

    public BulkPaymentWebServiceNewService() {
        super(__getWsdlLocation(), BULKPAYMENTWEBSERVICENEWSERVICE_QNAME);
    }

    public BulkPaymentWebServiceNewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BULKPAYMENTWEBSERVICENEWSERVICE_QNAME, features);
    }

    public BulkPaymentWebServiceNewService(URL wsdlLocation) {
        super(wsdlLocation, BULKPAYMENTWEBSERVICENEWSERVICE_QNAME);
    }

    public BulkPaymentWebServiceNewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BULKPAYMENTWEBSERVICENEWSERVICE_QNAME, features);
    }

    public BulkPaymentWebServiceNewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BulkPaymentWebServiceNewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (BULKPAYMENTWEBSERVICENEWSERVICE_EXCEPTION != null) {
            throw BULKPAYMENTWEBSERVICENEWSERVICE_EXCEPTION;
        }
        return BULKPAYMENTWEBSERVICENEWSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns BulkPaymentWebServiceNew
     */
    @WebEndpoint(name = "BulkPaymentWebServiceNewSoapPort")
    public BulkPaymentWebServiceNew getBulkPaymentWebServiceNewSoapPort() {
        return super.getPort(new QName("http://www.obopay.com/xml/bulkpayment/v1", "BulkPaymentWebServiceNewSoapPort"), BulkPaymentWebServiceNew.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BulkPaymentWebServiceNew
     */
    @WebEndpoint(name = "BulkPaymentWebServiceNewSoapPort")
    public BulkPaymentWebServiceNew getBulkPaymentWebServiceNewSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.obopay.com/xml/bulkpayment/v1", "BulkPaymentWebServiceNewSoapPort"), BulkPaymentWebServiceNew.class, features);
    }

}
