package org.muhia.app.psi.integ.wsdl.crba.transunion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ControllerKenya", targetNamespace = "http://ws.crbws.transunion.ke.co/")
@XmlSeeAlso({ObjectFactory.class})
public interface ControllerKenya {


    /**
     * @param password
     * @param code
     * @param phoneNumber
     * @param infinityCode
     * @param reportSector
     * @param message
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product401
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct401", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct401")
    @ResponseWrapper(localName = "getProduct401Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct401Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct401Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct401Response")
    Product401 getProduct401(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "phoneNumber", targetNamespace = "") String phoneNumber, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason, @WebParam(name = "message", targetNamespace = "") String message);

    /**
     * @param password
     * @param code
     * @param names
     * @param phoneNumber
     * @param infinityCode
     * @param documentNumber
     * @param reportSector
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product402
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct402", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct402")
    @ResponseWrapper(localName = "getProduct402Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct402Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct402Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct402Response")
    Product402 getProduct402(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "documentNumber", targetNamespace = "") String documentNumber, @WebParam(name = "names", targetNamespace = "") String names, @WebParam(name = "phoneNumber", targetNamespace = "") String phoneNumber, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param password
     * @param code
     * @param phoneNumber
     * @param infinityCode
     * @param reportSector
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product403
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct403", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct403")
    @ResponseWrapper(localName = "getProduct403Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct403Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct403Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct403Response")
    Product403 getProduct403(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "phoneNumber", targetNamespace = "") String phoneNumber, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param origin
     * @param transactionCode
     * @param transactionMobileNo
     * @param dest
     * @param transactionDate
     * @param transactionTime
     * @param transactionAccount
     * @param password
     * @param infinityCode
     * @param transactionAmount
     * @param senderNames
     * @param receivedTimeStamp
     * @param username
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product405
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct405", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct405")
    @ResponseWrapper(localName = "getProduct405Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct405Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct405Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct405Response")
    Product405 getProduct405(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "origin", targetNamespace = "") String origin, @WebParam(name = "dest", targetNamespace = "") String dest, @WebParam(name = "receivedTimeStamp", targetNamespace = "") String receivedTimeStamp, @WebParam(name = "transactionDate", targetNamespace = "") String transactionDate, @WebParam(name = "transactionTime", targetNamespace = "") String transactionTime, @WebParam(name = "transactionCode", targetNamespace = "") String transactionCode, @WebParam(name = "transactionMobileNo", targetNamespace = "") String transactionMobileNo, @WebParam(name = "transactionAccount", targetNamespace = "") String transactionAccount, @WebParam(name = "senderNames", targetNamespace = "") String senderNames, @WebParam(name = "transactionAmount", targetNamespace = "") String transactionAmount);

    /**
     * @param passportNo
     * @param code
     * @param telephoneWork
     * @param telephoneMobile
     * @param dateOfBirth
     * @param postalBoxNo
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param name4
     * @param name3
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param alienID
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product102
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct102", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct102")
    @ResponseWrapper(localName = "getProduct102Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct102Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct102Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct102Response")
    Product102 getProduct102(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param passportNo
     * @param code
     * @param telephoneWork
     * @param telephoneMobile
     * @param dateOfBirth
     * @param postalBoxNo
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param name4
     * @param name3
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param alienID
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product103
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct103", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct103")
    @ResponseWrapper(localName = "getProduct103Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct103Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct103Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct103Response")
    Product103 getProduct103(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product101
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct101", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct101")
    @ResponseWrapper(localName = "getProduct101Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct101Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct101Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct101Response")
    Product101 getProduct101(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param password
     * @param code
     * @param phoneNumber
     * @param infinityCode
     * @param reportSector
     * @param crn
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product110
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct110", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct110")
    @ResponseWrapper(localName = "getProduct110Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct110Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct110Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct110Response")
    Product110 getProduct110(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "crn", targetNamespace = "") int crn, @WebParam(name = "phoneNumber", targetNamespace = "") String phoneNumber, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param password
     * @param emailAddress
     * @param code
     * @param phoneNumber
     * @param infinityCode
     * @param reportSector
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product406
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct406", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct406")
    @ResponseWrapper(localName = "getProduct406Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct406Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct406Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct406Response")
    Product406 getProduct406(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "phoneNumber", targetNamespace = "") String phoneNumber, @WebParam(name = "emailAddress", targetNamespace = "") String emailAddress, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product118
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct118", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct118")
    @ResponseWrapper(localName = "getProduct118Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct118Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct118Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct118Response")
    Product118 getProduct118(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param password
     * @param code
     * @param infinityCode
     * @param username
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.CreditBal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCreditBal", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetCreditBal")
    @ResponseWrapper(localName = "getCreditBalResponse", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetCreditBalResponse")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getCreditBalRequest", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getCreditBalResponse")
    CreditBal getCreditBal(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product100
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct100", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct100")
    @ResponseWrapper(localName = "getProduct100Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct100Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct100Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct100Response")
    Product100 getProduct100(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product104
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct104", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct104")
    @ResponseWrapper(localName = "getProduct104Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct104Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct104Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct104Response")
    Product104 getProduct104(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param reportSector
     * @param companyName
     * @param companyRegNo
     * @param vatID
     * @param websiteAddress
     * @param postalBoxNo
     * @param physicalTown
     * @param companyRegDate
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param telephoneNo
     * @param faxNo
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product150
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct150", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct150")
    @ResponseWrapper(localName = "getProduct150Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct150Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct150Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct150Response")
    Product150 getProduct150(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "companyName", targetNamespace = "") String companyName, @WebParam(name = "companyRegNo", targetNamespace = "") String companyRegNo, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "vatID", targetNamespace = "") String vatID, @WebParam(name = "companyRegDate", targetNamespace = "") XMLGregorianCalendar companyRegDate, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneNo", targetNamespace = "") String telephoneNo, @WebParam(name = "faxNo", targetNamespace = "") String faxNo, @WebParam(name = "websiteAddress", targetNamespace = "") String websiteAddress, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param reportSector
     * @param companyName
     * @param companyRegNo
     * @param vatID
     * @param websiteAddress
     * @param postalBoxNo
     * @param physicalTown
     * @param companyRegDate
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param telephoneNo
     * @param faxNo
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product152
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct152", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct152")
    @ResponseWrapper(localName = "getProduct152Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct152Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct152Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct152Response")
    Product152 getProduct152(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "companyName", targetNamespace = "") String companyName, @WebParam(name = "companyRegNo", targetNamespace = "") String companyRegNo, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "vatID", targetNamespace = "") String vatID, @WebParam(name = "companyRegDate", targetNamespace = "") XMLGregorianCalendar companyRegDate, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneNo", targetNamespace = "") String telephoneNo, @WebParam(name = "faxNo", targetNamespace = "") String faxNo, @WebParam(name = "websiteAddress", targetNamespace = "") String websiteAddress, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param reportSector
     * @param companyName
     * @param companyRegNo
     * @param vatID
     * @param websiteAddress
     * @param postalBoxNo
     * @param physicalTown
     * @param companyRegDate
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param telephoneNo
     * @param faxNo
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product159
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct159", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct159")
    @ResponseWrapper(localName = "getProduct159Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct159Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct159Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct159Response")
    Product159 getProduct159(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "companyName", targetNamespace = "") String companyName, @WebParam(name = "companyRegNo", targetNamespace = "") String companyRegNo, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "vatID", targetNamespace = "") String vatID, @WebParam(name = "companyRegDate", targetNamespace = "") XMLGregorianCalendar companyRegDate, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneNo", targetNamespace = "") String telephoneNo, @WebParam(name = "faxNo", targetNamespace = "") String faxNo, @WebParam(name = "websiteAddress", targetNamespace = "") String websiteAddress, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product107
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct107", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct107")
    @ResponseWrapper(localName = "getProduct107Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct107Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct107Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct107Response")
    Product107 getProduct107(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product114
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct114", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct114")
    @ResponseWrapper(localName = "getProduct114Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct114Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct114Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct114Response")
    Product114 getProduct114(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product108
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct108", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct108")
    @ResponseWrapper(localName = "getProduct108Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct108Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct108Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct108Response")
    Product108 getProduct108(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product109
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct109", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct109")
    @ResponseWrapper(localName = "getProduct109Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct109Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct109Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct109Response")
    Product109 getProduct109(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product112
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct112", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct112")
    @ResponseWrapper(localName = "getProduct112Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct112Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct112Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct112Response")
    Product112 getProduct112(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product115
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct115", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct115")
    @ResponseWrapper(localName = "getProduct115Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct115Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct115Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct115Response")
    Product115 getProduct115(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product116
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct116", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct116")
    @ResponseWrapper(localName = "getProduct116Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct116Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct116Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct116Response")
    Product116 getProduct116(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param telephoneHome
     * @param physicalTown
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param nationalID
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param alienID
     * @param passportNo
     * @param telephoneWork
     * @param telephoneMobile
     * @param reportSector
     * @param dateOfBirth
     * @param postalBoxNo
     * @param name4
     * @param name3
     * @param physicalCountry
     * @param name2
     * @param serviceID
     * @param name1
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product105
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct105", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct105")
    @ResponseWrapper(localName = "getProduct105Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct105Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct105Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct105Response")
    Product105 getProduct105(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "name1", targetNamespace = "") String name1, @WebParam(name = "name2", targetNamespace = "") String name2, @WebParam(name = "name3", targetNamespace = "") String name3, @WebParam(name = "name4", targetNamespace = "") String name4, @WebParam(name = "nationalID", targetNamespace = "") String nationalID, @WebParam(name = "passportNo", targetNamespace = "") String passportNo, @WebParam(name = "serviceID", targetNamespace = "") String serviceID, @WebParam(name = "alienID", targetNamespace = "") String alienID, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "dateOfBirth", targetNamespace = "") XMLGregorianCalendar dateOfBirth, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneWork", targetNamespace = "") String telephoneWork, @WebParam(name = "telephoneHome", targetNamespace = "") String telephoneHome, @WebParam(name = "telephoneMobile", targetNamespace = "") String telephoneMobile, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param reportSector
     * @param companyName
     * @param companyRegNo
     * @param vatID
     * @param websiteAddress
     * @param postalBoxNo
     * @param physicalTown
     * @param companyRegDate
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param telephoneNo
     * @param faxNo
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product151
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct151", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct151")
    @ResponseWrapper(localName = "getProduct151Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct151Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct151Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct151Response")
    Product151 getProduct151(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "companyName", targetNamespace = "") String companyName, @WebParam(name = "companyRegNo", targetNamespace = "") String companyRegNo, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "vatID", targetNamespace = "") String vatID, @WebParam(name = "companyRegDate", targetNamespace = "") XMLGregorianCalendar companyRegDate, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneNo", targetNamespace = "") String telephoneNo, @WebParam(name = "faxNo", targetNamespace = "") String faxNo, @WebParam(name = "websiteAddress", targetNamespace = "") String websiteAddress, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param code
     * @param reportSector
     * @param companyName
     * @param companyRegNo
     * @param vatID
     * @param websiteAddress
     * @param postalBoxNo
     * @param physicalTown
     * @param companyRegDate
     * @param postalCountry
     * @param password
     * @param infinityCode
     * @param telephoneNo
     * @param faxNo
     * @param taxID
     * @param physicalAddress
     * @param postalTown
     * @param physicalCountry
     * @param username
     * @param reportReason
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.Product153
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct153", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct153")
    @ResponseWrapper(localName = "getProduct153Response", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetProduct153Response")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct153Request", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getProduct153Response")
    Product153 getProduct153(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode, @WebParam(name = "companyName", targetNamespace = "") String companyName, @WebParam(name = "companyRegNo", targetNamespace = "") String companyRegNo, @WebParam(name = "taxID", targetNamespace = "") String taxID, @WebParam(name = "vatID", targetNamespace = "") String vatID, @WebParam(name = "companyRegDate", targetNamespace = "") XMLGregorianCalendar companyRegDate, @WebParam(name = "postalBoxNo", targetNamespace = "") String postalBoxNo, @WebParam(name = "postalTown", targetNamespace = "") String postalTown, @WebParam(name = "postalCountry", targetNamespace = "") String postalCountry, @WebParam(name = "telephoneNo", targetNamespace = "") String telephoneNo, @WebParam(name = "faxNo", targetNamespace = "") String faxNo, @WebParam(name = "websiteAddress", targetNamespace = "") String websiteAddress, @WebParam(name = "physicalAddress", targetNamespace = "") String physicalAddress, @WebParam(name = "physicalTown", targetNamespace = "") String physicalTown, @WebParam(name = "physicalCountry", targetNamespace = "") String physicalCountry, @WebParam(name = "reportSector", targetNamespace = "") int reportSector, @WebParam(name = "reportReason", targetNamespace = "") int reportReason);

    /**
     * @param password
     * @param code
     * @param infinityCode
     * @param username
     * @return returns org.muhia.app.psi.integ.wsdl.crba.transunion.ServerInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerInfo", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetServerInfo")
    @ResponseWrapper(localName = "getServerInfoResponse", targetNamespace = "http://ws.crbws.transunion.ke.co/", className = "org.muhia.app.psi.integ.wsdl.crba.transunion.GetServerInfoResponse")
    @Action(input = "http://ws.crbws.transunion.ke.co/ControllerKenya/getServerInfoRequest", output = "http://ws.crbws.transunion.ke.co/ControllerKenya/getServerInfoResponse")
    ServerInfo getServerInfo(@WebParam(name = "username", targetNamespace = "") String username, @WebParam(name = "password", targetNamespace = "") String password, @WebParam(name = "code", targetNamespace = "") String code, @WebParam(name = "infinityCode", targetNamespace = "") String infinityCode);

}
